/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef ENGINE_PRIVATE_H
#define ENGINE_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"0.3.2.42"
#define VER_MAJOR	0
#define VER_MINOR	3
#define VER_RELEASE	2
#define VER_BUILD	42
#define COMPANY_NAME	""
#define FILE_VERSION	"0.3.2.42"
#define FILE_DESCRIPTION	""
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	""
#define PRODUCT_VERSION	""

#endif /*ENGINE_PRIVATE_H*/
